project:
  title: "algo-curve"

diagram:
  engine:
    tikz:
      header-includes:
        - '\usetikzlibrary{arrows}'
        
title: "Fast confidence bounds for the false discovery proportion 
  over a path of hypotheses"
# subtitle: ""
author:
  - name: Guillermo Durand
    corresponding: true
    email: guillermo.durand@universite-paris-saclay.fr
    url: https://durandg12.github.io/
    orcid: 0000-0003-4056-5631
    affiliations:
      - name: Université Paris-Saclay, CNRS, Inria, 91405, Orsay, France
        department: Laboratoire de Mathématiques d'Orsay
        url: https://www.imo.universite-paris-saclay.fr/fr/
date: last-modified
date-modified: last-modified
abstract: >+
  This paper presents a new algorithm (and an additional trick) 
  that allows to compute fastly 
  an entire curve of post hoc bounds for the False Discovery Proportion when the 
  underlying bound $V^*_{\mathfrak{R}}$ construction is based on a reference 
  family $\mathfrak{R}$ with a forest structure à la @MR4178188. 
  By an entire curve, we mean the values 
  $V^*_{\mathfrak{R}}(S_1),\dotsc,V^*_{\mathfrak{R}}(S_m)$ computed on a path 
  of increasing selection sets $S_1\subsetneq\dotsb\subsetneq S_m$, $|S_t|=t$. 
  The new algorithm leverages the fact that going from $S_t$ to $S_{t+1}$ 
  is done by adding only one hypothesis. Compared to a more naive approach,
  the new algorithm has a complexity in $O(m|\mathcal K|)$ instead of
  $O(m^2|\mathcal K|)$, where $|\mathcal K|$ is the cardinality of the family.
keywords: [multiple testing, algorithmic, post hoc inference, 
  false discovery proportion, confidence bound]
citation:
  type: article-journal
  container-title: "Computo"
  doi: "xxxx"
  url: https://computo.sfds.asso.fr/algo-curve
  publisher: "Société Française de Statistique"
  issn: "2824-7795"
bibliography: algo-curve.bib
github-user: durandg12
repo: "algo-curve"
draft: true # set to false once the build is running
published: false # will be set to true once accepted
number-sections: true
format:
  computo-html: 
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            tex: {
              tags: 'ams'
            }
          };
          </script>
    crossrefs-hover: false
  computo-pdf: 
    include-in-header:
      - text: |
          \usepackage{amsmath}
    cite-method: natbib
    natbiboptions: round
    keep-tex: true
    crossrefs-hover: false
    pdf-engine: pdflatex